### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by hackwaly** [faicker/greendns-stack#1]
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by faicker** [comment]
Hi, this is because your docker version is old to support compose-file version 2.4.
Commit of using minimum version 2.1 is pushed to master.
Version 2.1 requires docker version >= 1.12.0.
